# Configure here which dependency updates should be merged automatically.
- match:
    dependency_type: production
    update_type: "semver:patch"
- match:
    dependency_type: production
    update_type: "security:minor"
- match:
    dependency_type: development
    update_type: "semver:minor"
