/*global systemDictionary:true */
"use strict"

systemDictionary = {
    "panasonic-comfort-cloud adapter settings": {
        en: "Adapter settings for panasonic-comfort-cloud",
        de: "Adaptereinstellungen für panasonic-comfort-cloud",
        ru: "Настройки адаптера для panasonic-comfort-cloud",
        pt: "Configurações do adaptador para panasonic-comfort-cloud",
        nl: "Adapterinstellingen voor panasonic-comfort-cloud",
        fr: "Paramètres d'adaptateur pour panasonic-comfort-cloud",
        it: "Impostazioni dell'adattatore per panasonic-comfort-cloud",
        es: "Ajustes del adaptador para panasonic-comfort-cloud",
        pl: "Ustawienia adaptera dla panasonic-comfort-cloud",
        "zh-cn": "panasonic-comfort-cloud的适配器设置",
    },
    username: {
        en: "Username",
        de: "Benutzername",
        ru: "Опция 1",
        pt: "Opção 1",
        nl: "Optie 1",
        fr: "Option 1",
        it: "opzione 1",
        es: "Opción 1",
        pl: "opcja 1",
        "zh-cn": "选项1",
    },
    password: {
        en: "Password",
        de: "Passwort",
        ru: "option2",
        pt: "opção 2",
        nl: "Optie 2",
        fr: "Option 2",
        it: "opzione 2",
        es: "opcion 2",
        pl: "Opcja 2",
        "zh-cn": "选项2",
    },
    refreshIngerval: {
        en: "Refresh interval (m)",
        de: "Aktualisierungsinterval (m)",
        ru: "option2",
        pt: "opção 2",
        nl: "Optie 2",
        fr: "Option 2",
        it: "opzione 2",
        es: "opcion 2",
        pl: "Opcja 2",
        "zh-cn": "选项2",
    },
}
